//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final11.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employe
    {
        public int EPF_no { get; set; }
        public string Sname { get; set; }
        public string Fullname { get; set; }
        public string Office_Mobile { get; set; }
        public string Office_Land { get; set; }
        public string Office_fax { get; set; }
        public string Office_Intercom { get; set; }
        public string Office_Location { get; set; }
        public int sub_function_id { get; set; }
    
        public virtual sub_function sub_function { get; set; }
    }
}
