//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final11.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CorporationEntities : DbContext
    {
        public CorporationEntities()
            : base("name=CorporationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cFunction> cFunctions { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<employe> employes { get; set; }
        public virtual DbSet<sub_function> sub_function { get; set; }
    }
}
